version: "3"
services:
  rails_mysql:
    container_name: rails_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: railsdb
    ports:
      - "3306:3306"

  rails_web:
    container_name: rails_web
    build: .
    command: /bin/sh -c "rm -f /app_name/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    links:
      - rails_mysql
